### ISSUE TITLE
Do not encrypt salt

### ISSUE THREAD

**Issue by ilinum** [0x27/GitPass#2]
Salts are not meant to be encrypted, there's no point in doing that http://security.stackexchange.com/questions/66801/is-encrypting-salt-with-given-users-password-more-secure

**Comment by ilinum** [comment]
Actually, never mind. You're just encoding it in base64

**Comment by 0x27** [comment]
The reason for encoding it was because otherwise it tended to produce characters the JSON parser didn't like. Will document that though :)

**Comment by ilinum** [comment]
@0x27 cool, thanks!
